Document how to run example AttentionIsAllYouNeed
chengchingwen/Transformers.jl pull request #68
Opened 2021-07-19 16:04 UTC by Oblynx

2021-07-19 23:21 UTC, chengchingwen requested changes

2021-07-19 23:21 UTC, chengchingwen commented on example/AttentionIsAllYouNeed/README.md
> +This is an implementation of the seminal paper [Attention is all you need [annotated]](https://nlp.seas.harvard.edu/2018/04/03/attention.html)
Should point to the original paper
```suggestion
This is an implementation of the seminal paper [Attention is all you need](https://arxiv.org/abs/1706.03762)
```

2021-07-19 23:21 UTC, chengchingwen commented on example/AttentionIsAllYouNeed/README.md
> +The architecture is explained [here](https://medium.com/data-science-in-your-pocket/attention-is-all-you-need-understanding-with-example-c8d074c37767).
```suggestion
The architecture is explained [here](https://nlp.seas.harvard.edu/2018/04/03/attention.html).
```

2021-07-20 05:38 UTC, merged

2021-07-20 05:39 UTC, chengchingwen commented
Thanks!

2021-07-20 06:11 UTC, Oblynx commented
Thank you!